[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = false
fs_permissions = [{ access = "read", path = "./"}]

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536

[rpc_endpoints]
monad_testnet = "${MONAD_TESTNET_RPC_URL}"
monad_mainnet = "${MONAD_MAINNET_RPC_URL}"

[etherscan]
monad_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet-explorer.monad.xyz/api" }
monad_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer.monad.xyz/api" }
